### PR TITLE
import edit 

### PR DESCRIPTION
**Pull request by xn0px90**
Did all the changes with in Vim not ATOM.

### CODE REVIEW

**Comment by xn0px90** [comment]
I get the same error when i build the main repo as well. in my system running go 1.6

**Comment by bnagy** [comment]
Weird. Let me just do it in master. :) travis doesn't seem to recognise that tag, either, maybe 1.6.1. I'll mess with it.

**Comment by bnagy** [comment]
import "C" needs to be on a line by itself, not in an import group. Who knew? Push incoming.

**Comment by bnagy** [comment]
All green in master and next. Thanks for the patch!

**Pull request closed without merging**
